package com.fragmadata.mtm.enums.scheduler;

public enum EmailStatus {

    SUCCESS,
    FAILURE,
    SYSTEM_ERROR,
    VALIDATION,
    INFORMATION,
    READ_START,
    PENDING,
    READ_COMPLETE,
    QUEUED_FOR_SHEET_IDENTIFICATION,
    CONFIG_NOT_MATCHED,
    CONFIG_MATCHED_AND_STAGED_FOR_QUEUING,
    QUEUED_FOR_SHEET_PROCESSING,
    QUEUED_FOR_PROCESSING,
    SHEET_CONFIG_MISMATCHED,
    PARSING_FAILED,
    EMAIL_CONFIG_NOT_MATCHED,
    QUEUED_FOR_ATTACHMENT_IDENTIFICATION,
    PROCESSED,
    FAILED
}
