package com.fragmadata.mtm.enums.scheduler;

public enum Schedulers {

    EMAIL_POLLING_SCHEDULER,
    EMAIL_PROCESSING_SCHEDULER,
    ATTACHMENT_IDENTIFICATION_SCHEDULER,
    SHEET_IDENTIFICATION_SCHEDULER,
    SHEET_PROOCESSING_SCHEDULER,
    EMAIL_STATUS_TRACKING_SCHEDULER,
    FMC_FILE_GENERATION_SCHEDULER,
    Daily_FMC_FILE_GENERATION_SCHEDULER
}
